project_id = "qpozetnbnzdinqkrafze"

[functions.compress-tv-video]
verify_jwt = true

[functions.process-tv-with-gemini]
verify_jwt = true

[functions.process-press-pdf]
verify_jwt = true

[functions.check-pdf-job-status]
verify_jwt = true